[build]
watchPatterns = ["services/**"]

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# API Service
[[services]]
name = "mswd-api"
root = "services/api"

[services.build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[services.deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300

# Environment Variables for API
[services.variables]
PORT = "8000"
ENVIRONMENT = "production"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = "30"

# Worker Service
[[services]]
name = "mswd-worker"
root = "services/api"

[services.build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[services.deploy]
startCommand = "celery -A app.core.celery worker --loglevel=info"

# N8N Service
[[services]]
name = "mswd-n8n"
root = "."

[services.build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[services.deploy]
startCommand = "n8n start"

[services.variables]
N8N_BASIC_AUTH_ACTIVE = "true"
N8N_BASIC_AUTH_USER = "admin"
N8N_BASIC_AUTH_PASSWORD = "admin123"
WEBHOOK_URL = "https://mswd-n8n.railway.app"
GENERIC_TIMEZONE = "Asia/Manila"
DB_TYPE = "postgresdb"

# Frontend Service
[[services]]
name = "mswd-frontend"
root = "apps/web"

[services.build]
builder = "dockerfile"
dockerfilePath = "../../Dockerfile"

[services.deploy]
startCommand = "npm run build && npm run preview"

[services.variables]
VITE_API_BASE = "https://fastapi-production-9cc0.up.railway.app/api/v1"
VITE_FIREBASE_API_KEY = "AIzaSyB7Gacxs6y2h3ukiSmlWf1xHIhzwmD680I"
VITE_FIREBASE_AUTH_DOMAIN = "mswd-livelihood-web-app.firebaseapp.com"
VITE_FIREBASE_PROJECT_ID = "mswd-livelihood-web-app"
VITE_FIREBASE_STORAGE_BUCKET = "mswd-livelihood-web-app.firebasestorage.app"
VITE_FIREBASE_MESSAGING_SENDER_ID = "123619422952"
VITE_FIREBASE_APP_ID = "1:123619422952:web:bdf1b7ccfe15a969998f5d"
NODE_ENV = "production"